### ISSUE TITLE
CRASH: During Recover in Level 10

### ISSUE THREAD

**Issue by dantho** [rthorn/The-Barricade#3]
Console:
~\github\The-Barricade [main ≡]> python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::ffff:127.0.0.1 - - [17/Nov/2024 17:21:43] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('::ffff:127.0.0.1', 54361, 0, 0)
::ffff:127.0.0.1 - - [17/Nov/2024 17:21:44] "GET /style.css?v=1731882103813 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 1304, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 668, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 433, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 421, in handle_one_request
    method()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 675, in do_GET
    self.copyfile(f, self.wfile)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 875, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 826, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
::ffff:127.0.0.1 - - [17/Nov/2024 17:21:44] "GET /config.js?v=1731882104033 HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [17/Nov/2024 17:21:44] "GET /game.js?v=1731882104099 HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [17/Nov/2024 17:21:59] "GET / HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [17/Nov/2024 17:21:59] "GET /style.css?v=1731882119638 HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [17/Nov/2024 17:21:59] "GET /config.js?v=1731882119801 HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [17/Nov/2024 17:21:59] "GET /game.js?v=1731882119832 HTTP/1.1" 200 -

**Comment by dantho** [comment]
![image](https://github.com/user-attachments/assets/424546b4-ea4a-4147-822e-3c2ea1f832e8)

**Comment by rthorn** [comment]
If you're able to open the browser JS console when this happens, that would be a more useful error message than the python one.

**Comment by dantho** [comment]
Hasn't repeated since.  Closing
